template: |
  ## What’s Changed

  $CHANGES
version-resolver:
  major:
    labels:
      - "type: breaking"
  minor:
    labels:
      - "type: feature 🔨"
  patch:
    labels:
      - "type: bug 🐛"
  default: patch
categories:
  - title: '🚀 Features'
    labels: 
      - 'type: feature 🔨'
  - title: '🐛 Bug Fixes'
    labels:
      - 'type: bug 🐛'
