name: DEBUG

on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]
    
jobs:
    create_issue_branch_job:
        runs-on: ubuntu-latest
        steps:
        - name: Create Issue Branch
          id: cib
          uses: robvanderleek/create-issue-branch@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Echo branch name
          run: echo "${{ steps.cib.outputs.branchName }}"
          
#   create-issue-branch:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
        
#       - uses: robvanderleek/create-issue-branch@master
#         id: create-issue-branch
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - if: steps.create-issue-branch.outputs.branchName != ''
#         id: template
#         env:
#           ISSUE_BRANCH_NAME: ${{ steps.create-issue-branch.outputs.branchName }}
#         run: |
#           name=$ISSUE_BRANCH_NAME
#           if [[ $name =~ ^fix/ ]]; then \
#             template="bug.md"; \
#           elif [[ $name =~ ^feat/ ]]; then \
#             template="feature.md"; \
#           elif [[ $name =~ ^chore/ ]]; then \
#             template="chore.md"
#           elif [[ $name =~ ^docs/ ]]; then \
#             template="documentation.md"
#           fi
#           echo "::set-output name=template-name::$template"

#       - uses: mshick/add-pr-comment@v1
#         if: steps.create-issue-branch.outputs.branchName != ''
#         env:
#           PULL_REQUEST_URL: ${{ format('https://github.com/{0}/compare/{1}...{2}?quick_pull=1&template={3}', github.repository, 'trunk', steps.create-issue-branch.outputs.branchName, steps.template.outputs.template-name) }}
#         with:
#           message: |
#             **Hello**
#             ${{ env.PULL_REQUEST_URL }}
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           repo-token-user-login: "github-actions[bot]"
