name: DEBUG

on:
  pull_request:
    types: [opened, synchronize, review_requested]

jobs:
  pr-label-check:
    name: Release Label Present
    if: github.event.action == 'synchronize' || github.event.action == 'review_requested'
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
      - name: check for release label
        if: github.event.pull_request.labels == []
        run: |
          echo "::error ::PR must be labeled"
          exit 1
