name: TEST

on:
  pull_request:
    types: [opened, reopened]

jobs:
  clubhouse-link:
    name: clubhouse link
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'ch')
    steps:
      - name: debug
        run: |
          echo "branch: $GITHUB_HEAD_REF"
          
      - name: extract id
        id: extract-id
        run: |
          if [[ $GITHUB_HEAD_REF =~ ^ch([0-9]+) ]]; \
          then \
            echo "::set-output name=clubhouse-id::${BASH_REMATCH[1]}"; \
          fi

      - name: add pr link in comment
        if: steps.extract-id.outputs.clubhouse-id != ''
        uses: mshick/add-pr-comment@master
        with:
          message: |
            ## Related issue 
            [${{ steps.extract-id.outputs.clubhouse-id }}](https://app.clubhouse.io/takeshape/story/)
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"
