name: Workflow Sync

on:
  push:
    paths:
      - .github/workflows/workflow-sync.yml
      - .github/workflows/_pm_issues.yml
      - .github/workflows/_pm_pull-request.yml
      - .github/workflows/_pm_release.yml
      - .github/issue-branch.yml
      - .github/auto.json
      - .github/pr-labeler.yml
    branches:
      - trunk

env:
  TARGET_REPOS: |
    takeshape/shape-form
    takeshape/takeshape
    takeshape/takeshape-email
    takeshape/takeshape-gatsby
    takeshape/takeshape-routing
    takeshape/takeshape-samples
    takeshape/takeshape-skyword
    takeshape/takeshape.io
    takeshape/vm-nunjucks
  FILE_PATTERNS: |
    ^.github/workflows/_pm*
    ^.github/issue-branch.yml
    ^.github/auto.json
    ^.github/pr-labeler.yml
  COMMIT_MESSAGE: |
    .github workflow file sync [skip ci]

jobs:
  file-sync:
    name: file sync
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: syncing files
        uses: adrianjost/files-sync-action@v1.0.1
        with:
          FILE_PATTERNS: ${{ env.FILE_PATTERNS }}
          TARGET_REPOS: ${{ env.TARGET_REPOS }}
          GITHUB_TOKEN: ${{ secrets.LABEL_SYNC_TOKEN }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
