name: Workflow Sync

on:
  push:
    paths:
      - .github/workflows/workflow-sync.yml
      - .github/workflows/_pm_issues.yml
      - .github/workflows/_pm_pull-request.yml
      - .github/workflows/_pm_release.yml
      - .github/issue-branch.yml
      - .github/auto.json
      - .github/pr-labeler.yml
    branches:
      - trunk

env:
  DRY_RUN: false
  REPOSITORIES: |
    takeshape/shape-form
    takeshape/takeshape
    takeshape/takeshape-email
    takeshape/takeshape-gatsby
    takeshape/takeshape-routing
    takeshape/takeshape-samples
    takeshape/takeshape-skyword
    takeshape/takeshape.io
    takeshape/vm-nunjucks
  WORKFLOW_FILES: |
    ./.github/issue-branch.yml=../issue-branch.yml
    ./.github/auto.json=../auto.json
    ./.github/pr-labeler.yml=../pr-labeler.yml
    ./.github/workflows/_pm_issues.yml
    ./.github/workflows/_pm_pull-request.yml
    ./.github/workflows/_pm_release.yml

jobs:
  github-workflow-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@master
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.LABEL_SYNC_TOKEN }}
